php artisan make:model Dependent -m
php artisan make:model SymptomCheck -m
php artisan make:model Certificate -m
php artisan make:model NoteTemplate -m
php artisan make:model ChatbotSession -m
php artisan make:model Room -m
php artisan make:model BedAssignment -m
php artisan make:model Medication -m
php artisan make:model InventoryLevel -m
php artisan make:model DispensingRecord -m
php artisan make:model Shift -m
php artisan make:model LeaveRequest -m
php artisan make:model Equipment -m
php artisan make:model Announcement -m
php artisan make:model WhatsappLog -m
php artisan make:model SurveyResponse -m
php artisan make:model WebauthnKey -m
php artisan make:model DoctorPreference -m
php artisan make:model UserPreference -m
